name: Update Komac

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Update Komac
        uses: actions/github-script@v6.4.0
        with:
          script: |
            // get the latest release of Komac
            const {data: {tag_name: tagName, assets: [{browser_download_url: browserDownloadUrl}]}} = await github.rest.repos.getLatestRelease({
              owner: 'russellbanks',
              repo: 'Komac'
            })
            const komacJarUrl = browserDownloadUrl.replace(/Komac-[0-9.]+-all\.jar/, `Komac-${tagName.slice(1)}-all.jar`)
            core.info(`Komac's latest version: ${tagName}`)

            // get raw content of main.ts and dist/index.js
            const [mainTs, dist_indexJs] = await Promise.all([
              fetch('https://raw.githubusercontent.com/vedantmgoyal2009/winget-releaser/main/main.ts').then(res => res.text()),
              fetch('https://raw.githubusercontent.com/vedantmgoyal2009/winget-releaser/main/dist/index.js').then(res => res.text())
            ])

            // check if action is already using the latest version
            core.info(`Komac version in main.ts: ${mainTs.match(/Komac-[0-9.]+-all\.jar/)[0]}`)
            if (mainTs.includes(komacJarUrl) && dist_indexJs.includes(komacJarUrl)) {
              core.info('No need to update.')
              core.info(`Bye bye! ðŸ‘‹`)
              return
            }
            core.info('Updating komac in main.ts and dist/index.js...')

            // function to replace the url in the main.ts and dist/index.js
            function replaceUrl (text) {
              return text.replace(/https:\/\/github\.com\/russellbanks\/Komac\/releases\/download\/v[0-9.]+\/Komac-[0-9.]+-all\.jar/g, komacJarUrl)
            }

            // get latest commit sha and tree sha of the main branch
            const {data: {commit: {sha: mainBranchCommitSha, commit: {tree: {sha: mainBranchTreeSha}}}}} = await github.rest.repos.getBranch({
              owner: 'vedantmgoyal2009',
              repo: 'winget-releaser',
              branch: 'main'
            })

            // create tree with the updated files
            const {data: {sha: treeShaWithUpdatedFiles}} = await github.rest.git.createTree({
              owner: 'vedantmgoyal2009',
              repo: 'winget-releaser',
              tree: [
                {
                  path: 'main.ts',
                  mode: '100644',
                  type: 'blob',
                  content: replaceUrl(mainTs)
                },
                {
                  path: 'dist/index.js',
                  mode: '100644',
                  type: 'blob',
                  content: replaceUrl(dist_indexJs)
                }
              ],
              base_tree: mainBranchTreeSha
            })

            // create commit with the updated tree
            const {data: {sha: commitShaWithUpdatedFiles}} = await github.rest.git.createCommit({
              owner: 'vedantmgoyal2009',
              repo: 'winget-releaser',
              message: `Update Komac to ${tagName}`,
              tree: treeShaWithUpdatedFiles,
              parents: [mainBranchCommitSha]
            })

            // update the main branch with the new commit
            const {data: {object: {sha: mainBranchNewSha}}} = await github.rest.git.updateRef({
              owner: 'vedantmgoyal2009',
              repo: 'winget-releaser',
              ref: 'heads/main',
              sha: commitShaWithUpdatedFiles
            })

            // update version tag with the main branch
            await github.rest.git.updateRef({
              owner: 'vedantmgoyal2009',
              repo: 'winget-releaser',
              ref: `tags/${(await github.rest.repos.getLatestRelease({
                  owner: 'vedantmgoyal2009',
                  repo: 'winget-releaser'
                })).data.tag_name
              }`,
              sha: mainBranchNewSha
            })

            core.info('Updated Komac successfully.')
            core.info(`Bye bye! ðŸ‘‹`)
